version: '3.8'
services:

  web:
    build:
      context: ./shvirtd-example-python # путь до докерфайла
      dockerfile: Dockerfile.python # имя докерфайла
    container_name: web             # имя контейнера
    ports:                          # проброс портов
      - '5000:5000'
    restart: always                 # перезапуск контейнера
    networks:
      backend:                      # добавить в сеть backend
       ipv4_address: 172.20.0.5     # статический IPv4

  db:
    image: mysql:8.0   # версия снимка
    container_name: db # имя контейнера
    ports:             # проброс портов
      - '3306:3306'
    restart: always    # перезапуск контейнера
    env_file: .env     # файл с переменными
    volumes:           # том и проброс файла в директории
      - ./mysql/my.conf:/etc/mysql/my.cnf:ro
    environment:
      - TZ=Europe/Moscow # установка часового пояса МСК
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - DB_HOST:${DB_HOST}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_PASSWORD}
      - DB_NAME:${DB_NAME}
      # Все параметры описываем в файле .env в папке проекта
    networks:
      backend:                    # добавить в сеть backend
        ipv4_address: 172.20.0.10 # статический IPv4

  reverse-proxy:
    image: haproxy
    container_name: reverse-proxy
    restart: always
    ports:
    - '127.0.0.1:8080:8080'
    volumes:
    - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
    networks:
      backend:                    # добавить в сеть backend
        ipv4_address: 172.20.0.11 # статический IPv4

  ingress-proxy:
    image: nginx:latest
    container_name: ingress-proxy
    restart: always
    volumes:
    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw
    network_mode: host

networks:            # создание сети
  backend:           # название сети контейнеров
    driver: bridge   # тип драйвера сети
    ipam:            # описание параметров сети
      config:
        - subnet: 172.20.0.0/24 # подсеть
          gateway: 172.20.0.1   # шлюз
